<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = [
            /* zh-TW */
            ['name' => 'Reunion', 'code' => 'RE', 'lang' => 'zh-TW'],
            ['name' => '不丹', 'code' => 'BT', 'lang' => 'zh-TW'],
            ['name' => '中國', 'code' => 'CN', 'lang' => 'zh-TW'],
            ['name' => '中非共和國', 'code' => 'CF', 'lang' => 'zh-TW'],
            ['name' => '丹麥', 'code' => 'DK', 'lang' => 'zh-TW'],
            ['name' => '亞美尼亞', 'code' => 'AM', 'lang' => 'zh-TW'],
            ['name' => '亞賽拜然', 'code' => 'AZ', 'lang' => 'zh-TW'],
            ['name' => '以色列', 'code' => 'IL', 'lang' => 'zh-TW'],
            ['name' => '伊拉克', 'code' => 'IQ', 'lang' => 'zh-TW'],
            ['name' => '伊朗', 'code' => 'IR', 'lang' => 'zh-TW'],
            ['name' => '俄羅斯', 'code' => 'RU', 'lang' => 'zh-TW'],
            ['name' => '保加利亞', 'code' => 'BG', 'lang' => 'zh-TW'],
            ['name' => '克羅埃西亞', 'code' => 'HR', 'lang' => 'zh-TW'],
            ['name' => '冰島', 'code' => 'IS', 'lang' => 'zh-TW'],
            ['name' => '列支敦士登', 'code' => 'LI', 'lang' => 'zh-TW'],
            ['name' => '利比亞', 'code' => 'LY', 'lang' => 'zh-TW'],
            ['name' => '剛果', 'code' => 'CG', 'lang' => 'zh-TW'],
            ['name' => '剛果 - 民主共和國', 'code' => 'CD', 'lang' => 'zh-TW'],
            ['name' => '加彭', 'code' => 'GA', 'lang' => 'zh-TW'],
            ['name' => '加拿大', 'code' => 'CA', 'lang' => 'zh-TW'],
            ['name' => '加薩走廊', 'code' => 'GZ', 'lang' => 'zh-TW'],
            ['name' => '匈牙利', 'code' => 'HU', 'lang' => 'zh-TW'],
            ['name' => '北韓', 'code' => 'KP', 'lang' => 'zh-TW'],
            ['name' => '北馬里亞納群島', 'code' => 'MP', 'lang' => 'zh-TW'],
            ['name' => '千里達與托貝哥共和國', 'code' => 'TT', 'lang' => 'zh-TW'],
            ['name' => '南喬治亞及南三明治群島', 'code' => 'GS', 'lang' => 'zh-TW'],
            ['name' => '南極洲', 'code' => 'AQ', 'lang' => 'zh-TW'],
            ['name' => '南非', 'code' => 'ZA', 'lang' => 'zh-TW'],
            ['name' => '南韓', 'code' => 'KR', 'lang' => 'zh-TW'],
            ['name' => '卡達', 'code' => 'QA', 'lang' => 'zh-TW'],
            ['name' => '印尼', 'code' => 'ID', 'lang' => 'zh-TW'],
            ['name' => '印度', 'code' => 'IN', 'lang' => 'zh-TW'],
            ['name' => '厄利垂亞', 'code' => 'ER', 'lang' => 'zh-TW'],
            ['name' => '厄瓜多', 'code' => 'EC', 'lang' => 'zh-TW'],
            ['name' => '古巴', 'code' => 'CU', 'lang' => 'zh-TW'],
            ['name' => '可可斯群島', 'code' => 'CC', 'lang' => 'zh-TW'],
            ['name' => '台灣', 'code' => 'TW', 'lang' => 'zh-TW'],
            ['name' => '史瓦濟蘭', 'code' => 'SZ', 'lang' => 'zh-TW'],
            ['name' => '吉布地', 'code' => 'DJ', 'lang' => 'zh-TW'],
            ['name' => '吉爾吉斯', 'code' => 'KG', 'lang' => 'zh-TW'],
            ['name' => '吉里巴斯', 'code' => 'KI', 'lang' => 'zh-TW'],
            ['name' => '哈薩克', 'code' => 'KZ', 'lang' => 'zh-TW'],
            ['name' => '哥倫比亞', 'code' => 'CO', 'lang' => 'zh-TW'],
            ['name' => '哥斯達黎加', 'code' => 'CR', 'lang' => 'zh-TW'],
            ['name' => '喀麥隆', 'code' => 'CM', 'lang' => 'zh-TW'],
            ['name' => '喬治亞', 'code' => 'GE', 'lang' => 'zh-TW'],
            ['name' => '土庫曼', 'code' => 'TM', 'lang' => 'zh-TW'],
            ['name' => '土瓦魯', 'code' => 'TV', 'lang' => 'zh-TW'],
            ['name' => '土耳其', 'code' => 'TR', 'lang' => 'zh-TW'],
            ['name' => '地曼島', 'code' => 'IM', 'lang' => 'zh-TW'],
            ['name' => '坦尚尼亞', 'code' => 'TZ', 'lang' => 'zh-TW'],
            ['name' => '埃及', 'code' => 'EG', 'lang' => 'zh-TW'],
            ['name' => '塔吉克', 'code' => 'TJ', 'lang' => 'zh-TW'],
            ['name' => '塞內加爾', 'code' => 'SN', 'lang' => 'zh-TW'],
            ['name' => '塞席爾', 'code' => 'SC', 'lang' => 'zh-TW'],
            ['name' => '塞爾維亞蒙特內哥羅', 'code' => 'CS', 'lang' => 'zh-TW'],
            ['name' => '墨西哥', 'code' => 'MX', 'lang' => 'zh-TW'],
            ['name' => '多哥', 'code' => 'TG', 'lang' => 'zh-TW'],
            ['name' => '多明尼克', 'code' => 'DM', 'lang' => 'zh-TW'],
            ['name' => '多明尼加共和國', 'code' => 'DO', 'lang' => 'zh-TW'],
            ['name' => '奈及利亞', 'code' => 'NG', 'lang' => 'zh-TW'],
            ['name' => '奧地利', 'code' => 'AT', 'lang' => 'zh-TW'],
            ['name' => '委內瑞拉', 'code' => 'VE', 'lang' => 'zh-TW'],
            ['name' => '孟加拉', 'code' => 'BD', 'lang' => 'zh-TW'],
            ['name' => '安哥拉', 'code' => 'AO', 'lang' => 'zh-TW'],
            ['name' => '安地卡及巴布達', 'code' => 'AG', 'lang' => 'zh-TW'],
            ['name' => '安歸拉島', 'code' => 'AI', 'lang' => 'zh-TW'],
            ['name' => '安道爾共和國', 'code' => 'AD', 'lang' => 'zh-TW'],
            ['name' => '宏都拉斯', 'code' => 'HN', 'lang' => 'zh-TW'],
            ['name' => '密可羅尼西亞 - 聯邦', 'code' => 'FM', 'lang' => 'zh-TW'],
            ['name' => '寮國', 'code' => 'LA', 'lang' => 'zh-TW'],
            ['name' => '尼加拉瓜', 'code' => 'NI', 'lang' => 'zh-TW'],
            ['name' => '尼日', 'code' => 'NE', 'lang' => 'zh-TW'],
            ['name' => '尼泊爾', 'code' => 'NP', 'lang' => 'zh-TW'],
            ['name' => '巴哈馬', 'code' => 'BS', 'lang' => 'zh-TW'],
            ['name' => '巴基斯坦', 'code' => 'PK', 'lang' => 'zh-TW'],
            ['name' => '巴布亞紐幾內亞', 'code' => 'PG', 'lang' => 'zh-TW'],
            ['name' => '巴拉圭', 'code' => 'PY', 'lang' => 'zh-TW'],
            ['name' => '巴拿馬', 'code' => 'PA', 'lang' => 'zh-TW'],
            ['name' => '巴林', 'code' => 'BH', 'lang' => 'zh-TW'],
            ['name' => '巴西', 'code' => 'BR', 'lang' => 'zh-TW'],
            ['name' => '巴貝多', 'code' => 'BB', 'lang' => 'zh-TW'],
            ['name' => '布吉納法索', 'code' => 'BF', 'lang' => 'zh-TW'],
            ['name' => '布干維島', 'code' => 'BV', 'lang' => 'zh-TW'],
            ['name' => '希臘', 'code' => 'GR', 'lang' => 'zh-TW'],
            ['name' => '帛琉', 'code' => 'PW', 'lang' => 'zh-TW'],
            ['name' => '幾內亞', 'code' => 'GN', 'lang' => 'zh-TW'],
            ['name' => '幾內亞比索', 'code' => 'GW', 'lang' => 'zh-TW'],
            ['name' => '德國', 'code' => 'DE', 'lang' => 'zh-TW'],
            ['name' => '意大利', 'code' => 'IT', 'lang' => 'zh-TW'],
            ['name' => '愛沙尼亞', 'code' => 'EE', 'lang' => 'zh-TW'],
            ['name' => '愛爾蘭', 'code' => 'IE', 'lang' => 'zh-TW'],
            ['name' => '所羅門群島', 'code' => 'SB', 'lang' => 'zh-TW'],
            ['name' => '托克勞群島', 'code' => 'TK', 'lang' => 'zh-TW'],
            ['name' => '拉脫維亞', 'code' => 'LV', 'lang' => 'zh-TW'],
            ['name' => '挪威', 'code' => 'NO', 'lang' => 'zh-TW'],
            ['name' => '捷克共和國', 'code' => 'CZ', 'lang' => 'zh-TW'],
            ['name' => '摩洛哥', 'code' => 'MA', 'lang' => 'zh-TW'],
            ['name' => '摩爾多瓦', 'code' => 'MD', 'lang' => 'zh-TW'],
            ['name' => '摩納哥', 'code' => 'MC', 'lang' => 'zh-TW'],
            ['name' => '敘利亞', 'code' => 'SY', 'lang' => 'zh-TW'],
            ['name' => '教廷 (梵蒂岡城)', 'code' => 'VA', 'lang' => 'zh-TW'],
            ['name' => '斐濟', 'code' => 'FJ', 'lang' => 'zh-TW'],
            ['name' => '斯洛伐克', 'code' => 'SK', 'lang' => 'zh-TW'],
            ['name' => '斯洛維尼亞', 'code' => 'SI', 'lang' => 'zh-TW'],
            ['name' => '斯瓦巴德群島', 'code' => 'SJ', 'lang' => 'zh-TW'],
            ['name' => '斯里蘭卡', 'code' => 'LK', 'lang' => 'zh-TW'],
            ['name' => '新加坡', 'code' => 'SG', 'lang' => 'zh-TW'],
            ['name' => '新喀里多尼亞', 'code' => 'NC', 'lang' => 'zh-TW'],
            ['name' => '日本', 'code' => 'JP', 'lang' => 'zh-TW'],
            ['name' => '智利', 'code' => 'CL', 'lang' => 'zh-TW'],
            ['name' => '東加', 'code' => 'TO', 'lang' => 'zh-TW'],
            ['name' => '東帝汶', 'code' => 'TP', 'lang' => 'zh-TW'],
            ['name' => '東帝汶', 'code' => 'TL', 'lang' => 'zh-TW'],
            ['name' => '查德', 'code' => 'TD', 'lang' => 'zh-TW'],
            ['name' => '柬埔寨', 'code' => 'KH', 'lang' => 'zh-TW'],
            ['name' => '根西島', 'code' => 'GG', 'lang' => 'zh-TW'],
            ['name' => '格瑞那達', 'code' => 'GD', 'lang' => 'zh-TW'],
            ['name' => '格陵蘭', 'code' => 'GL', 'lang' => 'zh-TW'],
            ['name' => '模里西斯', 'code' => 'MU', 'lang' => 'zh-TW'],
            ['name' => '比利時', 'code' => 'BE', 'lang' => 'zh-TW'],
            ['name' => '汶萊', 'code' => 'BN', 'lang' => 'zh-TW'],
            ['name' => '沙地阿拉伯', 'code' => 'SA', 'lang' => 'zh-TW'],
            ['name' => '法國', 'code' => 'FR', 'lang' => 'zh-TW'],
            ['name' => '法國南方和南極洲', 'code' => 'TF', 'lang' => 'zh-TW'],
            ['name' => '法屬圭亞那', 'code' => 'GF', 'lang' => 'zh-TW'],
            ['name' => '法屬波里尼西亞', 'code' => 'PF', 'lang' => 'zh-TW'],
            ['name' => '法羅群島', 'code' => 'FO', 'lang' => 'zh-TW'],
            ['name' => '波多黎克', 'code' => 'PR', 'lang' => 'zh-TW'],
            ['name' => '波斯尼亞 - 赫塞哥維納', 'code' => 'BA', 'lang' => 'zh-TW'],
            ['name' => '波札那', 'code' => 'BW', 'lang' => 'zh-TW'],
            ['name' => '波蘭', 'code' => 'PL', 'lang' => 'zh-TW'],
            ['name' => '泰國', 'code' => 'TH', 'lang' => 'zh-TW'],
            ['name' => '海地', 'code' => 'HT', 'lang' => 'zh-TW'],
            ['name' => '澤西島', 'code' => 'JE', 'lang' => 'zh-TW'],
            ['name' => '澳洲', 'code' => 'AU', 'lang' => 'zh-TW'],
            ['name' => '澳門特別行政區', 'code' => 'MO', 'lang' => 'zh-TW'],
            ['name' => '烏克蘭', 'code' => 'UA', 'lang' => 'zh-TW'],
            ['name' => '烏干達', 'code' => 'UG', 'lang' => 'zh-TW'],
            ['name' => '烏拉圭', 'code' => 'UY', 'lang' => 'zh-TW'],
            ['name' => '烏茲別克', 'code' => 'UZ', 'lang' => 'zh-TW'],
            ['name' => '牙買加', 'code' => 'JM', 'lang' => 'zh-TW'],
            ['name' => '特克斯和凱科斯群島', 'code' => 'TC', 'lang' => 'zh-TW'],
            ['name' => '獅子山', 'code' => 'SL', 'lang' => 'zh-TW'],
            ['name' => '玻利維亞', 'code' => 'BO', 'lang' => 'zh-TW'],
            ['name' => '瑞典', 'code' => 'SE', 'lang' => 'zh-TW'],
            ['name' => '瑞士', 'code' => 'CH', 'lang' => 'zh-TW'],
            ['name' => '瓜地馬拉', 'code' => 'GT', 'lang' => 'zh-TW'],
            ['name' => '瓜達羅普', 'code' => 'GP', 'lang' => 'zh-TW'],
            ['name' => '瓦利斯群島和富圖納群島', 'code' => 'WF', 'lang' => 'zh-TW'],
            ['name' => '甘比亞', 'code' => 'GM', 'lang' => 'zh-TW'],
            ['name' => '白俄羅斯', 'code' => 'BY', 'lang' => 'zh-TW'],
            ['name' => '百慕達', 'code' => 'BM', 'lang' => 'zh-TW'],
            ['name' => '皮特凱恩群島', 'code' => 'PN', 'lang' => 'zh-TW'],
            ['name' => '盧旺達', 'code' => 'RW', 'lang' => 'zh-TW'],
            ['name' => '盧森堡', 'code' => 'LU', 'lang' => 'zh-TW'],
            ['name' => '直布羅陀', 'code' => 'GI', 'lang' => 'zh-TW'],
            ['name' => '祕魯', 'code' => 'PE', 'lang' => 'zh-TW'],
            ['name' => '福克蘭群島 (馬爾維納斯群島)', 'code' => 'FK', 'lang' => 'zh-TW'],
            ['name' => '科克群島', 'code' => 'CK', 'lang' => 'zh-TW'],
            ['name' => '科威特', 'code' => 'KW', 'lang' => 'zh-TW'],
            ['name' => '科摩洛', 'code' => 'KM', 'lang' => 'zh-TW'],
            ['name' => '突尼西亞', 'code' => 'TN', 'lang' => 'zh-TW'],
            ['name' => '立陶宛', 'code' => 'LT', 'lang' => 'zh-TW'],
            ['name' => '約旦', 'code' => 'JO', 'lang' => 'zh-TW'],
            ['name' => '約旦河西岸', 'code' => 'PS', 'lang' => 'zh-TW'],
            ['name' => '納米比亞', 'code' => 'NA', 'lang' => 'zh-TW'],
            ['name' => '紐埃島', 'code' => 'NU', 'lang' => 'zh-TW'],
            ['name' => '紐西蘭', 'code' => 'NZ', 'lang' => 'zh-TW'],
            ['name' => '索馬利亞', 'code' => 'SO', 'lang' => 'zh-TW'],
            ['name' => '維德角', 'code' => 'CV', 'lang' => 'zh-TW'],
            ['name' => '緬甸', 'code' => 'MM', 'lang' => 'zh-TW'],
            ['name' => '羅馬尼亞', 'code' => 'RO', 'lang' => 'zh-TW'],
            ['name' => '美國', 'code' => 'US', 'lang' => 'zh-TW'],
            ['name' => '美國本土外小島嶼', 'code' => 'UM', 'lang' => 'zh-TW'],
            ['name' => '美屬維爾京群島', 'code' => 'VI', 'lang' => 'zh-TW'],
            ['name' => '美屬薩摩亞', 'code' => 'AS', 'lang' => 'zh-TW'],
            ['name' => '聖克里斯多福', 'code' => 'KN', 'lang' => 'zh-TW'],
            ['name' => '聖匹島', 'code' => 'PM', 'lang' => 'zh-TW'],
            ['name' => '聖多美普林西比', 'code' => 'ST', 'lang' => 'zh-TW'],
            ['name' => '聖文森與格瑞那丁', 'code' => 'VC', 'lang' => 'zh-TW'],
            ['name' => '聖誕島', 'code' => 'CX', 'lang' => 'zh-TW'],
            ['name' => '聖赫勒拿島', 'code' => 'SH', 'lang' => 'zh-TW'],
            ['name' => '聖路西亞', 'code' => 'LC', 'lang' => 'zh-TW'],
            ['name' => '聖馬力諾', 'code' => 'SM', 'lang' => 'zh-TW'],
            ['name' => '肯亞', 'code' => 'KE', 'lang' => 'zh-TW'],
            ['name' => '芬蘭', 'code' => 'FI', 'lang' => 'zh-TW'],
            ['name' => '英國', 'code' => 'GB', 'lang' => 'zh-TW'],
            ['name' => '英屬印度洋領地', 'code' => 'IO', 'lang' => 'zh-TW'],
            ['name' => '英屬維爾京群島', 'code' => 'VG', 'lang' => 'zh-TW'],
            ['name' => '茅利塔尼亞', 'code' => 'MR', 'lang' => 'zh-TW'],
            ['name' => '荷屬安地列斯群島', 'code' => 'AN', 'lang' => 'zh-TW'],
            ['name' => '荷蘭', 'code' => 'NL', 'lang' => 'zh-TW'],
            ['name' => '莫桑比克', 'code' => 'MZ', 'lang' => 'zh-TW'],
            ['name' => '菲律賓', 'code' => 'PH', 'lang' => 'zh-TW'],
            ['name' => '萬那杜', 'code' => 'VU', 'lang' => 'zh-TW'],
            ['name' => '葉門', 'code' => 'YE', 'lang' => 'zh-TW'],
            ['name' => '葡萄牙', 'code' => 'PT', 'lang' => 'zh-TW'],
            ['name' => '蒙古', 'code' => 'MN', 'lang' => 'zh-TW'],
            ['name' => '蒙特色納島', 'code' => 'MS', 'lang' => 'zh-TW'],
            ['name' => '蒲隆地', 'code' => 'BI', 'lang' => 'zh-TW'],
            ['name' => '蓋亞那', 'code' => 'GY', 'lang' => 'zh-TW'],
            ['name' => '薩摩斯島', 'code' => 'WS', 'lang' => 'zh-TW'],
            ['name' => '薩爾瓦多', 'code' => 'SV', 'lang' => 'zh-TW'],
            ['name' => '蘇丹', 'code' => 'SD', 'lang' => 'zh-TW'],
            ['name' => '蘇利南', 'code' => 'SR', 'lang' => 'zh-TW'],
            ['name' => '衣索比亞', 'code' => 'ET', 'lang' => 'zh-TW'],
            ['name' => '西撒哈拉', 'code' => 'EH', 'lang' => 'zh-TW'],
            ['name' => '西班牙', 'code' => 'ES', 'lang' => 'zh-TW'],
            ['name' => '諾福克島', 'code' => 'NF', 'lang' => 'zh-TW'],
            ['name' => '諾魯', 'code' => 'NR', 'lang' => 'zh-TW'],
            ['name' => '象牙海岸', 'code' => 'CI', 'lang' => 'zh-TW'],
            ['name' => '貝南', 'code' => 'BJ', 'lang' => 'zh-TW'],
            ['name' => '貝里斯', 'code' => 'BZ', 'lang' => 'zh-TW'],
            ['name' => '賴比瑞亞', 'code' => 'LR', 'lang' => 'zh-TW'],
            ['name' => '賴索托', 'code' => 'LS', 'lang' => 'zh-TW'],
            ['name' => '賽普勒斯', 'code' => 'CY', 'lang' => 'zh-TW'],
            ['name' => '贊比亞', 'code' => 'ZM', 'lang' => 'zh-TW'],
            ['name' => '赤道幾內亞', 'code' => 'GQ', 'lang' => 'zh-TW'],
            ['name' => '赫德島及麥當勞群島', 'code' => 'HM', 'lang' => 'zh-TW'],
            ['name' => '越南', 'code' => 'VN', 'lang' => 'zh-TW'],
            ['name' => '辛巴威', 'code' => 'ZW', 'lang' => 'zh-TW'],
            ['name' => '迦納', 'code' => 'GH', 'lang' => 'zh-TW'],
            ['name' => '開曼群島', 'code' => 'KY', 'lang' => 'zh-TW'],
            ['name' => '關島', 'code' => 'GU', 'lang' => 'zh-TW'],
            ['name' => '阿富汗', 'code' => 'AF', 'lang' => 'zh-TW'],
            ['name' => '阿拉伯聯合大公國', 'code' => 'AE', 'lang' => 'zh-TW'],
            ['name' => '阿曼', 'code' => 'OM', 'lang' => 'zh-TW'],
            ['name' => '阿根廷', 'code' => 'AR', 'lang' => 'zh-TW'],
            ['name' => '阿爾及利亞', 'code' => 'DZ', 'lang' => 'zh-TW'],
            ['name' => '阿爾巴尼亞', 'code' => 'AL', 'lang' => 'zh-TW'],
            ['name' => '阿魯巴島', 'code' => 'AW', 'lang' => 'zh-TW'],
            ['name' => '香港', 'code' => 'HK', 'lang' => 'zh-TW'],
            ['name' => '馬丁尼克島', 'code' => 'MQ', 'lang' => 'zh-TW'],
            ['name' => '馬來西亞', 'code' => 'MY', 'lang' => 'zh-TW'],
            ['name' => '馬其頓 - 前南斯拉夫共和國', 'code' => 'MK', 'lang' => 'zh-TW'],
            ['name' => '馬利', 'code' => 'ML', 'lang' => 'zh-TW'],
            ['name' => '馬拉威', 'code' => 'MW', 'lang' => 'zh-TW'],
            ['name' => '馬歇爾群島', 'code' => 'MH', 'lang' => 'zh-TW'],
            ['name' => '馬爾他', 'code' => 'MT', 'lang' => 'zh-TW'],
            ['name' => '馬爾地夫', 'code' => 'MV', 'lang' => 'zh-TW'],
            ['name' => '馬約特島', 'code' => 'YT', 'lang' => 'zh-TW'],
            ['name' => '馬達加斯加', 'code' => 'MG', 'lang' => 'zh-TW'],
            ['name' => '黎巴嫩', 'code' => 'LB', 'lang' => 'zh-TW'],

            /* en */
            ['name' => 'Afghanistan', 'code' => 'AF', 'lang' => 'en'],
            ['name' => 'Albania', 'code' => 'AL', 'lang' => 'en'],
            ['name' => 'Algeria', 'code' => 'DZ', 'lang' => 'en'],
            ['name' => 'American Samoa', 'code' => 'AS', 'lang' => 'en'],
            ['name' => 'Andorra', 'code' => 'AD', 'lang' => 'en'],
            ['name' => 'Angola', 'code' => 'AO', 'lang' => 'en'],
            ['name' => 'Anguilla', 'code' => 'AI', 'lang' => 'en'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'lang' => 'en'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'lang' => 'en'],
            ['name' => 'Argentina', 'code' => 'AR', 'lang' => 'en'],
            ['name' => 'Armenia', 'code' => 'AM', 'lang' => 'en'],
            ['name' => 'Aruba', 'code' => 'AW', 'lang' => 'en'],
            ['name' => 'Australia', 'code' => 'AU', 'lang' => 'en'],
            ['name' => 'Austria', 'code' => 'AT', 'lang' => 'en'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'lang' => 'en'],
            ['name' => 'Bahamas', 'code' => 'BS', 'lang' => 'en'],
            ['name' => 'Bahrain', 'code' => 'BH', 'lang' => 'en'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'lang' => 'en'],
            ['name' => 'Barbados', 'code' => 'BB', 'lang' => 'en'],
            ['name' => 'Belarus', 'code' => 'BY', 'lang' => 'en'],
            ['name' => 'Belgium', 'code' => 'BE', 'lang' => 'en'],
            ['name' => 'Belize', 'code' => 'BZ', 'lang' => 'en'],
            ['name' => 'Benin', 'code' => 'BJ', 'lang' => 'en'],
            ['name' => 'Bermuda', 'code' => 'BM', 'lang' => 'en'],
            ['name' => 'Bhutan', 'code' => 'BT', 'lang' => 'en'],
            ['name' => 'Bolivia', 'code' => 'BO', 'lang' => 'en'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'lang' => 'en'],
            ['name' => 'Botswana', 'code' => 'BW', 'lang' => 'en'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'lang' => 'en'],
            ['name' => 'Brazil', 'code' => 'BR', 'lang' => 'en'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'lang' => 'en'],
            ['name' => 'British Virgin Islands', 'code' => 'VG', 'lang' => 'en'],
            ['name' => 'Brunei', 'code' => 'BN', 'lang' => 'en'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'lang' => 'en'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'lang' => 'en'],
            ['name' => 'Burundi', 'code' => 'BI', 'lang' => 'en'],
            ['name' => 'Cambodia', 'code' => 'KH', 'lang' => 'en'],
            ['name' => 'Cameroon', 'code' => 'CM', 'lang' => 'en'],
            ['name' => 'Canada', 'code' => 'CA', 'lang' => 'en'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'lang' => 'en'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'lang' => 'en'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'lang' => 'en'],
            ['name' => 'Chad', 'code' => 'TD', 'lang' => 'en'],
            ['name' => 'Chile', 'code' => 'CL', 'lang' => 'en'],
            ['name' => 'China', 'code' => 'CN', 'lang' => 'en'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'lang' => 'en'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'lang' => 'en'],
            ['name' => 'Colombia', 'code' => 'CO', 'lang' => 'en'],
            ['name' => 'Comoros', 'code' => 'KM', 'lang' => 'en'],
            ['name' => 'Congo', 'code' => 'CG', 'lang' => 'en'],
            ['name' => 'Congo - Democratic Republic of', 'code' => 'CD', 'lang' => 'en'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'lang' => 'en'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'lang' => 'en'],
            ['name' => 'Cote d\'Ivoire', 'code' => 'CI', 'lang' => 'en'],
            ['name' => 'Croatia', 'code' => 'HR', 'lang' => 'en'],
            ['name' => 'Cuba', 'code' => 'CU', 'lang' => 'en'],
            ['name' => 'Cyprus', 'code' => 'CY', 'lang' => 'en'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'lang' => 'en'],
            ['name' => 'Denmark', 'code' => 'DK', 'lang' => 'en'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'lang' => 'en'],
            ['name' => 'Dominica', 'code' => 'DM', 'lang' => 'en'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'lang' => 'en'],
            ['name' => 'East Timor', 'code' => 'TP', 'lang' => 'en'],
            ['name' => 'Ecuador', 'code' => 'EC', 'lang' => 'en'],
            ['name' => 'Egypt', 'code' => 'EG', 'lang' => 'en'],
            ['name' => 'El Salvador', 'code' => 'SV', 'lang' => 'en'],
            ['name' => 'Equitorial Guinea', 'code' => 'GQ', 'lang' => 'en'],
            ['name' => 'Eritrea', 'code' => 'ER', 'lang' => 'en'],
            ['name' => 'Estonia', 'code' => 'EE', 'lang' => 'en'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'lang' => 'en'],
            ['name' => 'Falkland Islands (Islas Malvinas)', 'code' => 'FK', 'lang' => 'en'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'lang' => 'en'],
            ['name' => 'Fiji', 'code' => 'FJ', 'lang' => 'en'],
            ['name' => 'Finland', 'code' => 'FI', 'lang' => 'en'],
            ['name' => 'France', 'code' => 'FR', 'lang' => 'en'],
            ['name' => 'French Guyana', 'code' => 'GF', 'lang' => 'en'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'lang' => 'en'],
            ['name' => 'French Southern and Antarctic Lands', 'code' => 'TF', 'lang' => 'en'],
            ['name' => 'Gabon', 'code' => 'GA', 'lang' => 'en'],
            ['name' => 'Gambia', 'code' => 'GM', 'lang' => 'en'],
            ['name' => 'Gaza Strip', 'code' => 'GZ', 'lang' => 'en'],
            ['name' => 'Georgia', 'code' => 'GE', 'lang' => 'en'],
            ['name' => 'Germany', 'code' => 'DE', 'lang' => 'en'],
            ['name' => 'Ghana', 'code' => 'GH', 'lang' => 'en'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'lang' => 'en'],
            ['name' => 'Greece', 'code' => 'GR', 'lang' => 'en'],
            ['name' => 'Greenland', 'code' => 'GL', 'lang' => 'en'],
            ['name' => 'Grenada', 'code' => 'GD', 'lang' => 'en'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'lang' => 'en'],
            ['name' => 'Guam', 'code' => 'GU', 'lang' => 'en'],
            ['name' => 'Guatemala', 'code' => 'GT', 'lang' => 'en'],
            ['name' => 'Guernsey', 'code' => 'GG', 'lang' => 'en'],
            ['name' => 'Guinea', 'code' => 'GN', 'lang' => 'en'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'lang' => 'en'],
            ['name' => 'Guyana', 'code' => 'GY', 'lang' => 'en'],
            ['name' => 'Haiti', 'code' => 'HT', 'lang' => 'en'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'lang' => 'en'],
            ['name' => 'Holy See (Vatican City)', 'code' => 'VA', 'lang' => 'en'],
            ['name' => 'Honduras', 'code' => 'HN', 'lang' => 'en'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'lang' => 'en'],
            ['name' => 'Hungary', 'code' => 'HU', 'lang' => 'en'],
            ['name' => 'Iceland', 'code' => 'IS', 'lang' => 'en'],
            ['name' => 'India', 'code' => 'IN', 'lang' => 'en'],
            ['name' => 'Indonesia', 'code' => 'ID', 'lang' => 'en'],
            ['name' => 'Iran', 'code' => 'IR', 'lang' => 'en'],
            ['name' => 'Iraq', 'code' => 'IQ', 'lang' => 'en'],
            ['name' => 'Ireland', 'code' => 'IE', 'lang' => 'en'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'lang' => 'en'],
            ['name' => 'Israel', 'code' => 'IL', 'lang' => 'en'],
            ['name' => 'Italy', 'code' => 'IT', 'lang' => 'en'],
            ['name' => 'Jamaica', 'code' => 'JM', 'lang' => 'en'],
            ['name' => 'Japan', 'code' => 'JP', 'lang' => 'en'],
            ['name' => 'Jersey', 'code' => 'JE', 'lang' => 'en'],
            ['name' => 'Jordan', 'code' => 'JO', 'lang' => 'en'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'lang' => 'en'],
            ['name' => 'Kenya', 'code' => 'KE', 'lang' => 'en'],
            ['name' => 'Kiribati', 'code' => 'KI', 'lang' => 'en'],
            ['name' => 'Kuwait', 'code' => 'KW', 'lang' => 'en'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'lang' => 'en'],
            ['name' => 'Laos', 'code' => 'LA', 'lang' => 'en'],
            ['name' => 'Latvia', 'code' => 'LV', 'lang' => 'en'],
            ['name' => 'Lebanon', 'code' => 'LB', 'lang' => 'en'],
            ['name' => 'Lesotho', 'code' => 'LS', 'lang' => 'en'],
            ['name' => 'Liberia', 'code' => 'LR', 'lang' => 'en'],
            ['name' => 'Libya', 'code' => 'LY', 'lang' => 'en'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'lang' => 'en'],
            ['name' => 'Lithuania', 'code' => 'LT', 'lang' => 'en'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'lang' => 'en'],
            ['name' => 'Macau', 'code' => 'MO', 'lang' => 'en'],
            ['name' => 'Macedonia - The Former Yugoslav Republic of', 'code' => 'MK', 'lang' => 'en'],
            ['name' => 'Madagascar', 'code' => 'MG', 'lang' => 'en'],
            ['name' => 'Malawi', 'code' => 'MW', 'lang' => 'en'],
            ['name' => 'Malaysia', 'code' => 'MY', 'lang' => 'en'],
            ['name' => 'Maldives', 'code' => 'MV', 'lang' => 'en'],
            ['name' => 'Mali', 'code' => 'ML', 'lang' => 'en'],
            ['name' => 'Malta', 'code' => 'MT', 'lang' => 'en'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'lang' => 'en'],
            ['name' => 'Martinique', 'code' => 'MQ', 'lang' => 'en'],
            ['name' => 'Mauritania', 'code' => 'MR', 'lang' => 'en'],
            ['name' => 'Mauritius', 'code' => 'MU', 'lang' => 'en'],
            ['name' => 'Mayotte', 'code' => 'YT', 'lang' => 'en'],
            ['name' => 'Mexico', 'code' => 'MX', 'lang' => 'en'],
            ['name' => 'Micronesia - Federated States of', 'code' => 'FM', 'lang' => 'en'],
            ['name' => 'Moldova', 'code' => 'MD', 'lang' => 'en'],
            ['name' => 'Monaco', 'code' => 'MC', 'lang' => 'en'],
            ['name' => 'Mongolia', 'code' => 'MN', 'lang' => 'en'],
            ['name' => 'Montserrat', 'code' => 'MS', 'lang' => 'en'],
            ['name' => 'Morocco', 'code' => 'MA', 'lang' => 'en'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'lang' => 'en'],
            ['name' => 'Myanmar', 'code' => 'MM', 'lang' => 'en'],
            ['name' => 'Namibia', 'code' => 'NA', 'lang' => 'en'],
            ['name' => 'Nauru', 'code' => 'NR', 'lang' => 'en'],
            ['name' => 'Nepal', 'code' => 'NP', 'lang' => 'en'],
            ['name' => 'Netherlands', 'code' => 'NL', 'lang' => 'en'],
            ['name' => 'Netherlands Antilles', 'code' => 'AN', 'lang' => 'en'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'lang' => 'en'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'lang' => 'en'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'lang' => 'en'],
            ['name' => 'Niger', 'code' => 'NE', 'lang' => 'en'],
            ['name' => 'Nigeria', 'code' => 'NG', 'lang' => 'en'],
            ['name' => 'Niue', 'code' => 'NU', 'lang' => 'en'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'lang' => 'en'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'lang' => 'en'],
            ['name' => 'North Korea', 'code' => 'KP', 'lang' => 'en'],
            ['name' => 'Norway', 'code' => 'NO', 'lang' => 'en'],
            ['name' => 'Oman', 'code' => 'OM', 'lang' => 'en'],
            ['name' => 'Pakistan', 'code' => 'PK', 'lang' => 'en'],
            ['name' => 'Palau', 'code' => 'PW', 'lang' => 'en'],
            ['name' => 'Panama', 'code' => 'PA', 'lang' => 'en'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'lang' => 'en'],
            ['name' => 'Paraguay', 'code' => 'PY', 'lang' => 'en'],
            ['name' => 'Peru', 'code' => 'PE', 'lang' => 'en'],
            ['name' => 'Philippines', 'code' => 'PH', 'lang' => 'en'],
            ['name' => 'Pitcairn Islands', 'code' => 'PN', 'lang' => 'en'],
            ['name' => 'Poland', 'code' => 'PL', 'lang' => 'en'],
            ['name' => 'Portugal', 'code' => 'PT', 'lang' => 'en'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'lang' => 'en'],
            ['name' => 'Qatar', 'code' => 'QA', 'lang' => 'en'],
            ['name' => 'Reunion', 'code' => 'RE', 'lang' => 'en'],
            ['name' => 'Romania', 'code' => 'RO', 'lang' => 'en'],
            ['name' => 'Russia', 'code' => 'RU', 'lang' => 'en'],
            ['name' => 'Rwanda', 'code' => 'RW', 'lang' => 'en'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'lang' => 'en'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'lang' => 'en'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'lang' => 'en'],
            ['name' => 'Samoa', 'code' => 'WS', 'lang' => 'en'],
            ['name' => 'San Marino', 'code' => 'SM', 'lang' => 'en'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'lang' => 'en'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'lang' => 'en'],
            ['name' => 'Senegal', 'code' => 'SN', 'lang' => 'en'],
            ['name' => 'Serbia and Montenegro', 'code' => 'CS', 'lang' => 'en'],
            ['name' => 'Seychelles', 'code' => 'SC', 'lang' => 'en'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'lang' => 'en'],
            ['name' => 'Singapore', 'code' => 'SG', 'lang' => 'en'],
            ['name' => 'Slovakia', 'code' => 'SK', 'lang' => 'en'],
            ['name' => 'Slovenia', 'code' => 'SI', 'lang' => 'en'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'lang' => 'en'],
            ['name' => 'Somalia', 'code' => 'SO', 'lang' => 'en'],
            ['name' => 'South Africa', 'code' => 'ZA', 'lang' => 'en'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'lang' => 'en'],
            ['name' => 'South Korea', 'code' => 'KR', 'lang' => 'en'],
            ['name' => 'Spain', 'code' => 'ES', 'lang' => 'en'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'lang' => 'en'],
            ['name' => 'St. Helena', 'code' => 'SH', 'lang' => 'en'],
            ['name' => 'St. Pierre and Miquelon', 'code' => 'PM', 'lang' => 'en'],
            ['name' => 'Sudan', 'code' => 'SD', 'lang' => 'en'],
            ['name' => 'Suriname', 'code' => 'SR', 'lang' => 'en'],
            ['name' => 'Svalbard', 'code' => 'SJ', 'lang' => 'en'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'lang' => 'en'],
            ['name' => 'Sweden', 'code' => 'SE', 'lang' => 'en'],
            ['name' => 'Switzerland', 'code' => 'CH', 'lang' => 'en'],
            ['name' => 'Syria', 'code' => 'SY', 'lang' => 'en'],
            ['name' => 'Taiwan', 'code' => 'TW', 'lang' => 'en'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'lang' => 'en'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'lang' => 'en'],
            ['name' => 'Thailand', 'code' => 'TH', 'lang' => 'en'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'lang' => 'en'],
            ['name' => 'Togo', 'code' => 'TG', 'lang' => 'en'],
            ['name' => 'Tokelau', 'code' => 'TK', 'lang' => 'en'],
            ['name' => 'Tonga', 'code' => 'TO', 'lang' => 'en'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'lang' => 'en'],
            ['name' => 'Tunisia', 'code' => 'TN', 'lang' => 'en'],
            ['name' => 'Turkey', 'code' => 'TR', 'lang' => 'en'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'lang' => 'en'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'lang' => 'en'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'lang' => 'en'],
            ['name' => 'Uganda', 'code' => 'UG', 'lang' => 'en'],
            ['name' => 'Ukraine', 'code' => 'UA', 'lang' => 'en'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'lang' => 'en'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'lang' => 'en'],
            ['name' => 'United States', 'code' => 'US', 'lang' => 'en'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'lang' => 'en'],
            ['name' => 'United States Virgin Islands', 'code' => 'VI', 'lang' => 'en'],
            ['name' => 'Uruguay', 'code' => 'UY', 'lang' => 'en'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'lang' => 'en'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'lang' => 'en'],
            ['name' => 'Venezuela', 'code' => 'VE', 'lang' => 'en'],
            ['name' => 'Vietnam', 'code' => 'VN', 'lang' => 'en'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'lang' => 'en'],
            ['name' => 'West Bank', 'code' => 'PS', 'lang' => 'en'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'lang' => 'en'],
            ['name' => 'Yemen', 'code' => 'YE', 'lang' => 'en'],
            ['name' => 'Zambia', 'code' => 'ZM', 'lang' => 'en'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'lang' => 'en'],

        ];
        DB::table('countries')->insert($countries);
    }
}
